### ISSUE TITLE
setting $service_provider = redhat causes service activation to fail

### ISSUE THREAD

**Issue by larsks** [soylent/konstantin-fluentd#14]
In `manifests/params.pp`, there is:

```
  # NOTE: Workaround for the following issue:                                   
  # https://tickets.puppetlabs.com/browse/PUP-5296                              
  if $::osfamily == 'redhat' and operatingsystemmajrelease < 7 {                
    $service_provider = 'redhat'                                                
  } else {                                                                      
    $service_provider = undef                                                   
  }                                                                             
```

Unfortunately, RHEL7 uses SystemD rather than the legacy init scripts managed by the `redhat` provider, so this, when giving the following manifest:

```
class {'fluentd':
  config_file      => '/etc/fluentd/fluent.conf',
  config_group     => fluentd,
  config_owner     => fluentd,
  config_path      => '/etc/fluentd/config.d',
  package_name     => fluentd,
  plugin_provider  => yum,
  repo_install     => false,
  service_name     => fluentd,
}
```

Results in the following error:

  Error: Could not enable fluentd: Execution of '/sbin/chkconfig --add fluentd' returned 1: error reading information on service fluentd: No such file or directory

Furthermore, while the `service.pp` manifest includes:

```
  provider   => $fluentd::service_provider,
```

This isn't exposed in `init.pp`, trying to add this to the calling manifest, like this:

```
class {'fluentd':
  config_file      => '/etc/fluentd/fluent.conf',
  config_group     => fluentd,
  config_owner     => fluentd,
  config_path      => '/etc/fluentd/config.d',
  package_name     => fluentd,
  plugin_provider  => yum,
  service_provider => systemd,
  repo_install     => false,
  service_name     => fluentd,
}
```

Results in an error:

```
Error: Invalid parameter service_provider on Class[Fluentd] at /root/foo.pp:11 on node overcloud-novacompute-0.localdomain
```

I think there are two separate problems here.
- The first is I hope not controversial: we need to expose the `service_provider` parameter in init.pp.
- Secondly, I'm not sure we should be explicitly setting `provider` here at all.  The manifest doesn't install an init script itself, which means that it has no way to tell whether or not it should be using the `redhat` or `systemd` provider, so it may as well just use the default.

It looks as if this problem may already be corrected in puppet, based on the comments on that linked bug report.

**Comment by soylent** [comment]
Hi,

Sorry for the late reply.

I am having problem reproducing this issue. The module works fine with the official RPM packages on CentOS 7. `td-agent` package provides init.d scripts and requires SysV init (https://github.com/treasure-data/omnibus-td-agent/blob/master/config/projects/td-agent2.rb#L38), so using `chkconfig` should not be a problem.

Do you use the official RPM packages? https://td-agent-package-browser.herokuapp.com/2/redhat/7/x86_64
