### ISSUE TITLE
Puppet provider 'tdagent' issue

### ISSUE THREAD

**Issue by jonapich** [soylent/konstantin-fluentd#22]
Hi,

For some reason I am unable to make this module work on the first puppet run, it always fails with this error:

`Failed to apply catalog: Parameter provider failed on Package[fluent-plugin-secure-forward]: Invalid package provider 'tdagent' at /etc/puppet/environments/development/modules/fluentd/manifests/plugin.pp:18`

It eventually works on the second run...

My config is as follow (repo-gpg added manually until puppet forge is updated):

`
  class {'::fluentd':
    repo_gpgkeyid => $fluentd_repo_gpgkeyid,
    plugins       => {
      'fluent-plugin-secure-forward' => {}
    }
  }`

I tried using 'include' and then 'fluentd::plugin' with the same outcome.

Any tips, or ideas to what could cause this?

**Comment by jonapich** [comment]
Turns out it was a puppet server misconfiguration. I'm running into a new problem (apt-update is scheduled, then it tries to pull the package but it fails because the source is configured but not updated, and then apt-update is called).

I'll play around and see how I can turn the tides on that one. Is it a known issue?

**Comment by jonapich** [comment]
I fixed it on my end in manifests/install.pp:

`
  package { $fluentd::package_name:
    ensure => $fluentd::package_ensure,
    require => Class['Apt::Update']
  } ->
`

Let me know if there was a cleaner way to do this ;)

**Comment by soylent** [comment]
Thanks for bringing up this issue, I'll look into it.

**Comment by soylent** [comment]
@jonapich 
Could you please check if [bugfix/apt-update](https://github.com/soylent/konstantin-fluentd/tree/bugfix/apt-update) branch resolves the issue?
