### ISSUE TITLE
Validate functions deprecated

### ISSUE THREAD

**Issue by jasondbaker** [soylent/konstantin-fluentd#24]
We recently upgraded from puppet 3.8 to 4.8 and now see warning messages related to the fluentd module. I guess this means the module will stop working on some future puppet release.

==> default: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Bool. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-d13e566bc1ef5c5b77f837a1b7abf98a/fluentd/manifests/init.pp", 28]:["/tmp/vagrant-puppet/modules-349b2fc5f7c6f9d1a4035056f56a248f/role/manifests/webserver.pp", 5]
==> default:    (at /tmp/vagrant-puppet/modules-d13e566bc1ef5c5b77f837a1b7abf98a/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
==> default: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::String. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-d13e566bc1ef5c5b77f837a1b7abf98a/fluentd/manifests/init.pp", 29]:["/tmp/vagrant-puppet/modules-349b2fc5f7c6f9d1a4035056f56a248f/role/manifests/webserver.pp", 5]
==> default:    (at /tmp/vagrant-puppet/modules-d13e566bc1ef5c5b77f837a1b7abf98a/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
==> default: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Absolute_Path. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-d13e566bc1ef5c5b77f837a1b7abf98a/fluentd/manifests/init.pp", 41]:["/tmp/vagrant-puppet/modules-349b2fc5f7c6f9d1a4035056f56a248f/role/manifests/webserver.pp", 5]
==> default:    (at /tmp/vagrant-puppet/modules-d13e566bc1ef5c5b77f837a1b7abf98a/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')

**Comment by soylent** [comment]
@jasondbaker Thanks, I'll update the module.
