### ISSUE TITLE
Fluent-bit support

### ISSUE THREAD

**Issue by yannh** [soylent/konstantin-fluentd#26]
Hi there! Nice module, would you consider pull requests for fluent-bit support? Or should that be a separate module? Thanks!

**Comment by soylent** [comment]
Hi @yannh 
It is better to create a separate Puppet module for that, fluent-bit is out of this module's scope

**Comment by yannh** [comment]
For reference I wrote one and published it: https://github.com/yannh/puppet-fluent_bit
Obviously it is missing a lot of documentation / tests in comparison to your fluentd module, and also has support for less platforms... But it' s a start? I started with your module as base and went from there, so thanks a lot!

**Comment by soylent** [comment]
Nice, great job!
