### ISSUE TITLE
Upgrade to support latest puppetlabs/apt

### ISSUE THREAD

**Issue by cristianbalan-mf** [soylent/konstantin-fluentd#30]
At the moment the dependency states `puppetlabs/apt (2.x)` while apt is in its version 4. To me would be enough the 3 for now. When upgrading apt, a Warning is thrown on the puppetserver when listing the modules.

**Comment by soylent** [comment]
@cristianbalan Could you please provide more info about the warning

**Comment by cristianbalan** [comment]
Hi soylent, I simply get this:

> Warning: Module 'puppetlabs-apt' (v3.0.0) fails to meet some dependencies:
>   'konstantin-fluentd' (v0.9.0) requires 'puppetlabs-apt' (v2.x)

**Comment by cristianbalan-mf** [comment]
Hi @soylent , I simply get this:

> Warning: Module 'puppetlabs-apt' (v3.0.0) fails to meet some dependencies:
>   'konstantin-fluentd' (v0.9.0) requires 'puppetlabs-apt' (v2.x)

**Comment by soylent** [comment]
Resolved in v0.10.0
