### ISSUE TITLE
Use of HTTP Without TLS 

### ISSUE THREAD

**Issue by akondasif** [soylent/konstantin-fluentd#34]
Greetings,

I am a security researcher, who is looking for security smells in Puppet scripts. I found instances where the HTTP protocol is used instead of HTTPS (HTTP with TLS). According to the Common Weakness Enumeration organization this is a security weakness (https://cwe.mitre.org/data/definitions/319.html).  I was wondering why HTTP is used? Is it because of lack of tool support?

I am trying to find out if developers are forced to adopt bad practices due to lack of tool support when it comes to the HTTPS protocol. Maybe it is due to dependency on a resource that uses HTTP?    

Any feedback is appreciated.  

Source: https://github.com/soylent/konstantin-fluentd/blob/master/manifests/params.pp (line#8, 14)

**Comment by soylent** [comment]
Hey Akond

Good catch, thank you! Base url of the td-agent repo is according to the official documentation
https://docs.fluentd.org/v1.0/articles/install-by-rpm
Specifically: https://toolbelt.treasuredata.com/sh/install-redhat-td-agent3.sh

**Comment by akondasif** [comment]
Thanks for the feedback. 
I also assumed the same, this smell occurs because of lacking tool support. Thanks for confirming.

**Comment by akondasif** [comment]
I am closing the issue, but please re-open if further discussion is necessary.
